services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # เปิดพอร์ต 27017 ของคอนเทนเนอร์ไปยังพอร์ต 27017 ของโฮสต์
    env_file:
      - .env # โหลดตัวแปร environment จากไฟล์ .env.docker
    volumes:
      - mongo_data:/data/db # เชื่อมต่อ volume ไปยัง path เก็บข้อมูลของ MongoDB

volumes:
  mongo_data:
    driver: local # ใช้ driver local เพื่อเก็บข้อมูลลงบนเครื่องโฮสต์
