services:
  mongodb:
    image: mongo:latest
    container_name: trainify-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - trainify-network

  server:
    build:
      context: ./server
    container_name: trainify-server
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/Trainify
      - PORT=${PORT}
      - SECRET_KEY=${Secret_Key}
      - TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENCRYPTION_IV=${ENCRYPTION_IV}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${Trainify_Email}
      - SMTP_PASS=${Trainify_Email_Password}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - trainify-network

  client:
    build:
      context: ./client
    container_name: trainify-client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: yarn dev --host 0.0.0.0
    environment:
      - VITE_API_URL=http://server:3000/api
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - trainify-network

  # เพิ่ม service สำหรับนำเข้าข้อมูลเริ่มต้น
  data-import:
    image: mongo:latest
    container_name: trainify-data-import
    depends_on:
      - mongodb
    volumes:
      - ./import-data:/import-data
      - ./import-data.sh:/import-data.sh
    command: >
      bash -c "chmod +x /import-data.sh && sleep 10 && /import-data.sh"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Trainify
      - DATA_DIR=/import-data
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - SUPER_ADMIN_FIRST_NAME=${SUPER_ADMIN_FIRST_NAME}
      - SUPER_ADMIN_LAST_NAME=${SUPER_ADMIN_LAST_NAME}
      - SUPER_ADMIN_PHONE=${SUPER_ADMIN_PHONE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENCRYPTION_IV=${ENCRYPTION_IV}
    networks:
      - trainify-network

networks:
  trainify-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
