services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment: .env
    volumes:
      - mongo-data:/data/db

  data-import:
    image: mongo:latest
    container_name: trainify-data-import
    depends_on:
      - mongodb
    volumes:
      - ./import-data:/import-data
      - ./import-data.sh:/import-data.sh
    command: >
      bash -c "chmod +x /import-data.sh && sleep 10 && /import-data.sh"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/trainify
      - DATA_DIR=/import-data
    networks:
      - trainify-network

  server:
    build:
      context: ./server
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    command: yarn dev
    environment: .env
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    working_dir: /app
    volumes:
      - ./client:/src
    ports:
      - "3100:3000"
    command: yarn dev
    depends_on:
      - server

volumes:
  mongo-data:
networks:
  trainify-network:
    external: true
